### ISSUE TITLE
Relationships linking mental/bodily state to sensors

### ISSUE THREAD

**Issue by binarybottle** [ChildMindInstitute/mhdb#28]
We should relate:
(1) mental/bodily state
(2) measurable characteristic of mental/bodily state
(3) quantity to measure
(4) location of measurement 
(5) sensor
(6) device (links to information like makers, models, characteristics of device, etc.) 

Three examples adapted from Anirudh's google doc:
  - (1) attention (2) brain electrical activity (3) electric field potential (4) scalp (5) electrode (6) EEG
  - (1) reciprocity (2) facial expression (3) image (4) periphery (5) camera (6) camera
  - (1) pain (2) HRV (3) light reflectance (4) fingertip (5) PPG (6) PPG finger clip?

I just want to note that we should acknowledge that we are merely inferring (2).  In the first example, we are inferring brain electrical activity, but actually measuring scalp field potentials.  In the second example, we are inferring something about facial expression, but are actually relying on human judgment (FACS) or measuring anthropometric measures from extracted facial features.

**Comment by shnizzedy** [comment]
I struggle with these labeled-node/unlabeled-edge examples, for two main reasons.
1. Without specifying the relationships, we increase the chances of miscommunication.
2. We'll need to encode the relationships as well as the entities in the database.

To the point of organization, I think a spreadsheet is the wrong medium for this exploration, for these reasons:
1. The number of steps between device and mental/bodily state will not be consistent
2. The paths between device and mental/bodily state will not always be linear
3. The paths that are the same shape and size will not necessarily use the same steps.

The [type of diagram](https://docs.google.com/drawings/d/1f2wSEcsIcTsZloNBORSgmsLP--zacj-eZ4njqnBfXoA/edit?usp=sharing) we've been working with in issue #25 is, to me, a much more appropriate format.

Short of diagramming, I also think you could better express these examples in plain text, e.g.,
the third example above can be more precisely expressed as
   
* (1) pain *is inferred from* **(** (7) _an algorithm **and** (2) HRV **and** (2) skin conductance **)**
  (2) HRV *is inferred from* **(** (7) _an algorithm A **and** (2) heart rate **)**
  (2) heart rate *is inferred from* **(** (7) _an algorithm B **and** **(** (3) light reflectance *at* (4) fingertip **))** 
  **(** (3) light reflectance *at* (4) fingertip **)** *is measured by* (5) PPG *is included in* (6) PMD-200
  (2) skin conductance *is inferred from* **(** (7) _an algorithm C **and** **(**  (3) electrodermal activity *at* (4) fingertip **))**
  **(**  (3) electrodermal activity *at* (4) fingertip **)** *is measured by* (5) EDA sensor *is included in* (6) PMD-200
  (6) PMD-200 *is manufactured by* (8) Medasense

or
[![almond pain 1](https://user-images.githubusercontent.com/5974438/31734237-136ead36-b40c-11e7-87ac-2b25a1a93b8a.png)](https://docs.google.com/drawings/d/1resdy7KH7o5cMfkUhLgQu8NJLg6OW_PG7gsuPS_J2bI/edit?usp=sharing)

I don't know how that kind of complexity can be clearly expressed in a spreadsheet.

(P.S. I have (2) & (3) as the same shape and color in the above diagram because I still don't understand where or why to draw the line between these classes of entity)

**Comment by anirudh4792** [comment]
In response to arno,

'we are merely inferring' - this resolves my concern that sometimes, claims are made by the apps. 
In the second example, a facial recognition algorithm has been used by the app but I added FACS as another way of measuring facial expressions to highlight that many methods may be used.
I have added (7) as how the device does the measurement to represent algorithms etc.

Here are the other examples configured to the above structure

(1) mental/bodily state
(2) measurable characteristic of mental/bodily state
(3) quantity to measure
(4) location of measurement
(5) sensor
(6) device (links to information like makers, models, characteristics of device, etc.)

- (1) pain (2) skin conductance (3) electrodermal activity (4) fingertip (5) EDA sensor (6) Medasense
	
- (1) pain (2) heart rate variability (3) blood property change (4) fingertip (5) PPG (6) Medasense	

- (2) salinity/amount of sweat (3) reactions with chemical reagents that result in visible color changes (4) skin, forearm or back (5) microfluidic channel system (6) wearable microfluidic electronic device
																	
- (1) tense, focused, or calm state of mind (2) respiration (3) expansion and contraction of the torso (4) torso (5) force sensors (6) spire
																			
- (1) night terrors (2) myoclonic twitches, jerks, shaking (3) movement (4) wrist (5) accelerometer or piezoelectric sensor (6) nightwear	

- (1) ability/willingness to speak in social situations (2) voice (3) audio (4) chest (5) microphone (6) lena audio device	

- (1) mania (2) voice (3) increase in rate, rhythm and volume (4) external (5) microphone (6) priori (7) algorithm - analysed by computer software

- (1) depression  (2) voice (3) decrease in rate, rhythm and volume (4) external (5) microphone (6) priori (7) algorithm - analysed by computer software

- (1) anxiety due to eating/feelings of overeating (2) quakes that rise around the skin of the neck	 (3) tremors/vibrations (4) throat (5) piezoelectric sensors (6) accubite

- (1) physical and emotional response - positive social relationship (2) heart rate variability	 (3) Blood Volume Pulse (BVP) (4) wrist (5) PPG (6) pplkpr (7) emotion classification algorithm	

- (2) peripheral skin temperature (3) temperature (4) wrist (5) infrared thermophile (6) E4

**Comment by anirudh4792** [comment]
In response to Jon, 

1) Thank you - I have no problems to move away from a spreadsheet format to represent such examples as you have elegantly done. However, how would we input this information into the database eventually (I was under the impression that we were pulling from the sheet into the database)?

2) "(P.S. I have (2) & (3) as the same shape and color in the above diagram because I still don't understand where or why to draw the line between these classes of entity)"
(2) measurable characteristic of mental/bodily state
(3) quantity to measure

We could do what we did for the 'SymptomsAllinOne' sheet where we had all entries in a single column and mapped them to each other within the same column vs associating them with indices in different worksheets as we are doing now. 

3) Once we all agree on a structure, I hope to make lists of (1), (2) (3), (4), (5), (6); and probably map them through indices while also adding what Jon suggested (eg defining relationships between them) or any other appropriate way to do it

4) I will also classify our neutral behaviors and add them into one of our lists (1-6)

**Comment by binarybottle** [comment]
Jon -- Absolutely agree about identifying links, using graphs instead of spreadsheets, and taking advantage of all that linked data has to offer us to establish meaningful relationships.  Thank you for taking care in reframing the example as a flowchart and with marked up text.

Anirudh -- Please be careful with your examples.  "blood property change" is too vague to be a quantity to measure, respiration could be written as "expansion and contraction of the torso during respiration" while (3) would be "movement" just like with night terrors...

**Comment by anirudh4792** [comment]
Thank you. I have re-written the ones that I felt merited change.

(1) tense, focused, or calm state of mind (2) expansion and contraction of the torso during respiration (3) movement (4) torso (5) force sensors (6) spire
                                                                   vs
(1) tense, focused, or calm state of mind (2) respiration (3) expansion and contraction of the torso (4) torso (5) force sensors (6) spire

(1) pain (2) heart rate variability (3) how? (4) fingertip (5) PPG (6) Medasense
                                                                vs
(1) pain (2) heart rate variability (3) blood property change (4) fingertip (5) PPG (6) Medasense

(1) mania (2) voice (3) increase in rate, rhythm and volume (4) external (5) microphone (6) priori (7) algorithm - analysed by computer software
                                                               vs
(1) mania (2)  increase in rate, rhythm and volume of voice  (3) increase in rate, rhythm and volume of voice (4) external (5) microphone (6) priori (7) algorithm - analysed by computer software

(1) depression (2) voice (3) decrease in rate, rhythm and volume (4) external (5) microphone (6) priori (7) algorithm - analysed by computer software
                                                                     vs
(1) depression (2) decrease in rate, rhythm and volume of voice (3) decrease in rate, rhythm and volume of voice (4) external (5) microphone (6) priori (7) algorithm - analysed by computer software

(1) anxiety due to eating/feelings of overeating (2) quakes that rise around the skin of the neck (3) tremors/vibrations (4) throat (5) piezoelectric sensors (6) accubite
                                                        vs
(1) anxiety due to eating/feelings of overeating (2) quakes that rise around the skin of the neck while swallowing (3) tremors/vibrations (4) throat (5) piezoelectric sensors (6) accubite

**Comment by shnizzedy** [comment]
@anirudh4792:
1. At this point, I think it's more important to be clear than to be in a particular format. The only code we have written for pulling things into the database are the specific sheets we already have. Whatever format we use for additional data will need fresh code, even if it's a spreadsheet. Many (most? all?) graphing apps can export to [DOT](https://en.wikipedia.org/wiki/DOT_(graph_description_language)) and/or [SVG](https://en.wikipedia.org/wiki/Scalable_Vector_Graphics) from which the journey to turtle is short (maybe shorter than the journey from a spreadsheet workbook to turtle). We could also build these prototype graphs in Protégé.
2. Isn't a "measurable characteristic of mental/bodily state" a "quantity to measure"? Isn't any corporeal or mental "quantity to measure" a "measurable characteristic of mental/bodily state"? Won't we be able to tell if a "quantity to measure"/"measurable characteristic" is "of mental/bodily state" by usage? If we are going to draw these lines in the encoding, why not separate "measurable characteristic of mental state", "measurable characteristic of bodily state" and "measurable characteristic of extrapersonal state"?
3. That would be how I would attack this if I *had* to use spreadsheets, but I agree with your earlier critique that bridge-index relationship keys are not very human-readable. I'm unconvinced that we need to put this in sheets, though I do think "lists of (1), (2) (3), (4), (5), (6)" could be quite helpful in defining each of those parent classes or categories.

---

@binarybottle: I'll say we're all welcome since that exercise was as much for me as for everyone else. I used @anirudh4792's shape and color markup from issue #25, so thanks to him for that clarity.

---

@anirudh4792: In the rewritten examples above, is "how?" a blank node?

Also, voice is such an interesting thing to try to isolate and quantify. 
[!["Ursula stealing Carl Kasell's voice for her home answering machine" by Topher McCulloch](https://user-images.githubusercontent.com/5974438/31738386-7a4ab17e-b418-11e7-9c0b-af91a4e2e93a.jpg)](https://www.flickr.com/photos/tofu_mugwump/36633543154/in/photolist-npwYPn-nDYEJ7-fMY5mM-XPbu61-N4EyTu-N4ExNJ-MZbEFB-Ma1y2W-z92dt7-zKCJBQ-A7125Z-z2eSWs-z9mvc8)

**Comment by anirudh4792** [comment]
Thanks for the clarification that it is possible (if not easier) to pull from graphs rather than spreadsheets. Totally agree that interpreting and visualizing things from a graphical diagram is way cooler than doing so from a spreadsheet.

I really like your cartoons/gifs (along the lines of avatars). I am thinking of assigning such pictures to our core neutral behaviors (a magnifying glass to represent attention to detail for example). It also helps us go closer to Arno's taxonomy paper where entires could be converted, represented and compared as symbols

**Comment by anirudh4792** [comment]
I am creating lists (from our 15 examples + neutral behaviors) for 1-6. 

We previously had (1) mental/physiological state and (2) measurable bodily state/bodily condition but now, we have (1) mental/bodily state, (2) measurable characteristic of mental/bodily state, (3) quantity to measure and I feel a behavior could fall under any of the three.

Here is an example of the list

(1) mental/physiological state 
pain
tense, focused, or calm state of mind
night terrors
ability/willingness to speak in social situations 
sharing emotions
socio-emotional reciprocity

(2) measurable bodily state/bodily condition
motor tics <eye blinking, shoulder shrugging, extension of extremities, simultaneous head turning, copropraxia, echopraxia>
vocal tics <throat clearing often caused by contraction of the diaphragm or muscles of the oropharynx, sniffing often caused by contraction of the diaphragm or muscles of the oropharynx, grunting often caused by contraction of the diaphragm or muscles of the oropharynx, palilalia, echolalia, coprolalia>
Palpitations
accelerated heart rate
Sweating
Trembling
shaking
Feelings of shortness of breath
feelings of smothering
Feelings of choking
chest pain

I feel having the distinction between bodily state and mental state would be useful. We could form sub groups (50 core neutral behaviors) between these.

**Comment by shnizzedy** [comment]
I *love* words but often find other media to be more effective and/or efficient at communicating. [Creative Commons Search](https://search.creativecommons.org/) is my go-to for media that I don't make myself.

**Comment by anirudh4792** [comment]
Thanks jon! @binarybottle I liked this! 
**Enter your search query**
Parents add a query - I want something that I can.. or a core neutral behavior (eg attention)

**Search using**
We would have our different components (symptoms, questions, people, apps, measures etc.). They could turn on multiple options (eg symptoms mapped to questions)

![screen shot 2017-10-18 at 5 41 07 pm](https://user-images.githubusercontent.com/10529973/31744156-c166ce4a-b42b-11e7-92b0-1e79a4e8f5ca.png)

**Comment by binarybottle** [comment]
this issue seems to be moving in directions of front end development and sensor/symptom mapping in other issue(s).  please refer future readers to relevant issues and close, or migrate extant issues to their own issues that are properly labeled.
