### ISSUE TITLE
Review intensity questions (neutral behavior + intensity)

### ISSUE THREAD

**Issue by anirudh4792** [ChildMindInstitute/mhdb#35]
Why/Points to note

It is the first set of questions that would be asked to the user to ascertain strengths, typical ability and weaknesses which would be used to generate follow up questions (frequency, context etc.)

Ability has/can often been merged with intensity _(I noted that ability can be made more efficient if combined with intensity - eg I cannot to can use nonverbal behaviors is made more efficient by I cannot use NCBs even with assistance <symbols, pictures> to I rely on and can only use NCBs.)_

Intensity is the only dimension that features opposite behaviors and extreme behavior _(eg is very easily distracted to cannot stop focussing)_

Intensity is sometimes combined with other dimensions like frequency _(eg I never seek social situations as I am fearful of being exposed to scrutiny to I cannot stop seeking social situations and be active in them <very dependent on others>)_

**Comment by binarybottle** [comment]
I believe intensity is particularly useful for signs (severity of tremors) but can be useful in symptoms as well (severity of hallucinations).  Perhaps we can avoid using intensity when other dimensions are more descriptive, but I think it has its place.  Is the issue here to include ability as an explicit dimension, or as in implicit dimension?  What is to be done to close this issue?
