### ISSUE TITLE
Sample form for lead questions

### ISSUE THREAD

**Issue by anirudh4792** [ChildMindInstitute/mhdb#49]
I really did try to understand what you were saying with the voting system, but I think I am lost. Here are two attempts of me trying to implement this. Thank you for your patience, and if this doesnt work, please let me know and I would be happy to learn. The new google forms is terrible and I preferred using the old one. Also, google forms cannot have two answer types (eg text and mcq (for voting) under one question)

1) editable version: https://docs.google.com/forms/d/e/1FAIpQLSfHocu9M5jpVO2P9797T2q8iWY7-lPwY_kipO-OYPoB888IFw/viewform?usp=send_form
Please add your lead questions in place of 'your name' + placeholder by editing the form
The person who fills the lead questions last will have to send the form to all three of us for the voting

2) text based answer version: https://docs.google.com/forms/d/e/1FAIpQLScEqVHPMiNMPZWfuLmipAXXwYm-Y29LxLU18BjTC1bE7-NhBg/viewform?usp=send_form
I have sent you the form, for you to add your lead question in the text box (other's responses will not be seen by you). 
I have activated a 'publish and show a public link to form results' option OR you will view the responses since you are collaborators
You would then vote by re-editing your forms/change my  responses

**Comment by shnizzedy** [comment]
I think your option 1 was so close to what @binarybottle suggested.

Instead of putting in placeholders and requiring us to edit the form directly, just add an "ADD OTHER" option to each multiple-choice question, keep responses editable, and you're golden. I made [a copy](https://docs.google.com/forms/d/1nMg7sP80sF12K2wzTckiYH_tU-b9-y05DG388RHoyDQ/edit?uiv=1) to try it out, and [it seems to work just right](https://docs.google.com/forms/d/e/1FAIpQLSfqcHkockEh5ULR7MyGbpGr1G6lERta07n3TndVRd2LPnZd-A/viewform).

Unfortunately, I didn't see an easier way to create all the questions than to copy-paste. The [populate-from-a-sheet add-on that I was thinking of](https://chrome.google.com/webstore/detail/dynamic-fields/ipeckgnbnbjgljjnpajhafjmnliihdef?utm_source=permalink) only updates options within a given question from a spreadsheet column as far as I can tell.

**Comment by shnizzedy** [comment]
[HTML forms @ W3Schools](https://www.w3schools.com/html/html_forms.asp)

**Comment by anirudh4792** [comment]
@binarybottle After a quick discussion with Jon where we explored options on Google Forms, I feel option 1 is the easiest for all concerned (2 steps - add your answer as an extra option by editing the form; vote once three options are present)

Regarding HTML, I can learn somewhat to code in HTML and create a form online. I look forward to learning this. What I did not understand was the backend part with python and excel

**Comment by binarybottle** [comment]
I just filled out your first questionnaire in a google form.  This format works fine for voting on wording.

**Comment by shnizzedy** [comment]
Working from [revised structure for neutral states & lead questions](https://docs.google.com/spreadsheets/d/1REHmDXldCZ_L403Zq0N0LdhwNNEAXEIJHcNHzOIjnSQ/edit?ts=5a16249e#gid=0), I'm starting to encode the relationships from this workbook as described in this diagram: 
![neutral_behavior_structure](https://user-images.githubusercontent.com/5974438/33224009-fd70566c-d132-11e7-8a82-d85d00830169.png)

**Comment by binarybottle** [comment]
This issue is subsumed within issue #61 -- closing this issue.
